CREATE SCHEMA IF NOT EXISTS edu;
SET search_path TO edu;
-- Схема БД для системы рейтинга школ (PostgreSQL)
-- Назначение: хранение справочников, данных ЕГЭ/приёма/профориентации и результатов аналитики (запросы, выборки, рейтинги, карточки, экспорт)

BEGIN;

-- Источник данных для сопоставления школ (фиксированный набор источников)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'school_source') THEN
    CREATE TYPE school_source AS ENUM ('EGE', 'ONE_C', 'BITRIX24');
  END IF;
END$$;

-- Тип набора данных ЕГЭ: факт (actual) или план/ожидание (plan)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ege_dataset_kind') THEN
    CREATE TYPE ege_dataset_kind AS ENUM ('actual', 'plan');
  END IF;
END$$;

-- Регион (субъект РФ)
CREATE TABLE IF NOT EXISTS region (
    region_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE
);

-- Муниципалитет внутри региона
CREATE TABLE IF NOT EXISTS municipality (
    municipality_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id       INTEGER NOT NULL REFERENCES region(region_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
    name            TEXT NOT NULL,
    CONSTRAINT uq_municipality_region_name UNIQUE (region_id, name)
);

-- Школа (основной справочник)
CREATE TABLE IF NOT EXISTS school (
    school_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipality_id INTEGER NOT NULL REFERENCES municipality(municipality_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
    full_name       TEXT NOT NULL,
    short_name      TEXT,
    address         TEXT,
    website         TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_school_municipality_full_name UNIQUE (municipality_id, full_name)
);

-- Профиль школы (у одной школы может быть несколько профилей)
CREATE TABLE IF NOT EXISTS school_profile (
    profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE
);

-- Связь "школа–профиль" (M:N)
CREATE TABLE IF NOT EXISTS school_profile_link (
    school_id  INTEGER NOT NULL REFERENCES school(school_id)
               ON UPDATE CASCADE ON DELETE CASCADE,
    profile_id INTEGER NOT NULL REFERENCES school_profile(profile_id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (school_id, profile_id)
);

-- Сопоставление школы между источниками (ЕГЭ / 1С / Битрикс24)
-- Для каждой школы в каждом источнике может быть максимум один внешний ключ.
CREATE TABLE IF NOT EXISTS school_external_key (
    ext_key_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES school(school_id)
                    ON UPDATE CASCADE ON DELETE CASCADE,
    source_name     school_source NOT NULL,
    external_key    TEXT NOT NULL,
    normalized_name TEXT,
    CONSTRAINT uq_source_external_key UNIQUE (source_name, external_key),
    CONSTRAINT uq_school_source UNIQUE (school_id, source_name)
);

-- Предмет ЕГЭ (справочник)
-- min_passing_score – минимальный порог (если хранится без детализации по годам).
CREATE TABLE IF NOT EXISTS ege_subject (
    subject_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL UNIQUE,
    min_passing_score SMALLINT,
    CONSTRAINT chk_subject_min_score CHECK (min_passing_score IS NULL OR (min_passing_score BETWEEN 0 AND 100))
);

-- ЕГЭ по школе за год (итоги по всем предметам)
CREATE TABLE IF NOT EXISTS ege_school_year (
    ege_school_year_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          INTEGER NOT NULL REFERENCES school(school_id)
                       ON UPDATE CASCADE ON DELETE CASCADE,
    year               SMALLINT NOT NULL,
    kind               ege_dataset_kind NOT NULL DEFAULT 'actual',
    graduates_total    INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT chk_ege_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_graduates_total CHECK (graduates_total >= 0),
    CONSTRAINT uq_ege_school_year UNIQUE (school_id, year, kind)
);

-- ЕГЭ по предмету (детализация "школа–год–тип–предмет")
-- Для kind = 'actual' заполняются показатели ЕГЭ (participants_cnt, avg_score и т.д.).
-- Для kind = 'plan' заполняется chosen_cnt (сколько выбрали предмет).
CREATE TABLE IF NOT EXISTS ege_school_subject_stat (
    ege_school_subject_stat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ege_school_year_id         INTEGER NOT NULL REFERENCES ege_school_year(ege_school_year_id)
                               ON UPDATE CASCADE ON DELETE CASCADE,
    subject_id                 INTEGER NOT NULL REFERENCES ege_subject(subject_id)
                               ON UPDATE CASCADE ON DELETE RESTRICT,

    participants_cnt  INTEGER,
    not_passed_cnt    INTEGER,
    high_80_99_cnt    INTEGER,
    score_100_cnt     INTEGER,
    avg_score         NUMERIC(5,2),

    chosen_cnt        INTEGER,

    CONSTRAINT chk_participants_nonneg CHECK (participants_cnt IS NULL OR participants_cnt >= 0),
    CONSTRAINT chk_not_passed_nonneg CHECK (not_passed_cnt IS NULL OR not_passed_cnt >= 0),
    CONSTRAINT chk_high_nonneg CHECK (high_80_99_cnt IS NULL OR high_80_99_cnt >= 0),
    CONSTRAINT chk_100_nonneg CHECK (score_100_cnt IS NULL OR score_100_cnt >= 0),
    CONSTRAINT chk_not_passed_le_part CHECK (
        participants_cnt IS NULL OR not_passed_cnt IS NULL OR not_passed_cnt <= participants_cnt
    ),
    CONSTRAINT chk_100_le_part CHECK (
        participants_cnt IS NULL OR score_100_cnt IS NULL OR score_100_cnt <= participants_cnt
    ),
    CONSTRAINT chk_80_99_le_part CHECK (
        participants_cnt IS NULL OR high_80_99_cnt IS NULL OR high_80_99_cnt <= participants_cnt
    ),
    CONSTRAINT chk_avg_score CHECK (avg_score IS NULL OR (avg_score BETWEEN 0 AND 100)),
    CONSTRAINT chk_chosen_nonneg CHECK (chosen_cnt IS NULL OR chosen_cnt >= 0),

    CONSTRAINT uq_ege_school_year_subject UNIQUE (ege_school_year_id, subject_id)
);

-- Институт (подразделение университета)
CREATE TABLE IF NOT EXISTS institute (
    institute_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE
);

-- Направление подготовки (принадлежит институту)
CREATE TABLE IF NOT EXISTS study_program (
    program_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institute_id INTEGER NOT NULL REFERENCES institute(institute_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    code         VARCHAR(20) NOT NULL UNIQUE,
    name         TEXT NOT NULL,
    level        VARCHAR(20), -- бакалавриат | специалитет | магистратура (если нужно)
    is_active    BOOLEAN NOT NULL DEFAULT TRUE
);

-- Требования ЕГЭ по направлению
-- weight: фиксированные значения 1/2/3; weight=1 трактуется как обязательный предмет.
CREATE TABLE IF NOT EXISTS program_ege_requirement (
    req_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id INTEGER NOT NULL REFERENCES study_program(program_id)
               ON UPDATE CASCADE ON DELETE CASCADE,
    subject_id INTEGER NOT NULL REFERENCES ege_subject(subject_id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
    role       VARCHAR(10) NOT NULL,  -- required | choice
    weight     SMALLINT NOT NULL DEFAULT 1,
    min_score  SMALLINT,

    CONSTRAINT chk_req_role CHECK (role IN ('required', 'choice')),
    CONSTRAINT chk_req_weight CHECK (weight IN (1, 2, 3)),
    CONSTRAINT chk_weight1_required CHECK (weight <> 1 OR role = 'required'),
    CONSTRAINT chk_req_min_score CHECK (min_score IS NULL OR (min_score BETWEEN 0 AND 100)),
    CONSTRAINT uq_program_subject UNIQUE (program_id, subject_id)
);

-- Профориентационные мероприятия (в систему попадают только проведённые)
CREATE TABLE IF NOT EXISTS prof_event (
    event_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     INTEGER NOT NULL REFERENCES school(school_id)
                  ON UPDATE CASCADE ON DELETE CASCADE,
    institute_id  INTEGER NOT NULL REFERENCES institute(institute_id)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
    event_date    DATE NOT NULL,
    coverage_cnt  INTEGER NOT NULL DEFAULT 0,
    event_type    VARCHAR(50),
    external_key  TEXT,

    CONSTRAINT chk_coverage_nonneg CHECK (coverage_cnt >= 0)
);

-- Итоги приёма по школе за год (агрегаты)
CREATE TABLE IF NOT EXISTS school_admission_stat (
    adm_stat_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES school(school_id)
                        ON UPDATE CASCADE ON DELETE CASCADE,
    year                SMALLINT NOT NULL,
    applicants_cnt      INTEGER NOT NULL DEFAULT 0,
    enrolled_cnt        INTEGER NOT NULL DEFAULT 0,
    enrolled_avg_score  NUMERIC(5,2),
    external_key        TEXT,

    CONSTRAINT chk_adm_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_applicants_nonneg CHECK (applicants_cnt >= 0),
    CONSTRAINT chk_enrolled_nonneg CHECK (enrolled_cnt >= 0),
    CONSTRAINT chk_enrolled_le_applicants CHECK (enrolled_cnt <= applicants_cnt),
    CONSTRAINT chk_enrolled_avg_score_range CHECK (enrolled_avg_score IS NULL OR (enrolled_avg_score BETWEEN 0 AND 100)),
    CONSTRAINT uq_school_adm_year UNIQUE (school_id, year)
);

-- Детализация приёма по направлениям (опционально, если данные есть)
-- Позволяет строить отчёты "школа → направления/институты", а не только агрегаты по школе.
CREATE TABLE IF NOT EXISTS school_admission_detail (
    detail_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adm_stat_id    INTEGER NOT NULL REFERENCES school_admission_stat(adm_stat_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
    program_id     INTEGER NOT NULL REFERENCES study_program(program_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    applicants_cnt INTEGER NOT NULL DEFAULT 0,
    enrolled_cnt   INTEGER NOT NULL DEFAULT 0,
    avg_score      NUMERIC(5,2),

    CONSTRAINT chk_adm_det_app_nonneg CHECK (applicants_cnt >= 0),
    CONSTRAINT chk_adm_det_enr_nonneg CHECK (enrolled_cnt >= 0),
    CONSTRAINT chk_adm_det_enr_le_app CHECK (enrolled_cnt <= applicants_cnt),
    CONSTRAINT chk_adm_det_avg_score CHECK (avg_score IS NULL OR (avg_score BETWEEN 0 AND 100)),
    CONSTRAINT uq_adm_stat_program UNIQUE (adm_stat_id, program_id)
);

-- Аналитический запрос (параметры фильтрации для отбора школ и расчёта рейтинга)
CREATE TABLE IF NOT EXISTS analytics_request (
    request_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by   VARCHAR(100),
    request_name VARCHAR(200),
    scenario     VARCHAR(12) NOT NULL,   -- selection | search
    year_basis   SMALLINT NOT NULL,      -- базовый год расчётов
    only_active  BOOLEAN NOT NULL DEFAULT TRUE,
    min_students INTEGER,
    max_students INTEGER,
    notes        TEXT,

    CONSTRAINT chk_req_scenario CHECK (scenario IN ('selection', 'search')),
    CONSTRAINT chk_req_year_basis CHECK (year_basis BETWEEN 2000 AND 2100),
    CONSTRAINT chk_req_students CHECK (
        (min_students IS NULL OR min_students >= 0) AND
        (max_students IS NULL OR max_students >= 0) AND
        (min_students IS NULL OR max_students IS NULL OR min_students <= max_students)
    )
);

-- Универсальная таблица множественного выбора (фильтров) для аналитического запроса
-- Сокращает количество связующих таблиц, сохраняя ссылочную целостность (FK) и нормализацию.
CREATE TABLE IF NOT EXISTS analytics_request_filter (
    filter_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    INTEGER NOT NULL REFERENCES analytics_request(request_id)
                  ON UPDATE CASCADE ON DELETE CASCADE,

    filter_type   VARCHAR(30) NOT NULL, -- region | municipality | institute | school_profile | program | subject | school

    region_id       INTEGER REFERENCES region(region_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    municipality_id INTEGER REFERENCES municipality(municipality_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    institute_id    INTEGER REFERENCES institute(institute_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    profile_id      INTEGER REFERENCES school_profile(profile_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    program_id      INTEGER REFERENCES study_program(program_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    subject_id      INTEGER REFERENCES ege_subject(subject_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    school_id       INTEGER REFERENCES school(school_id) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- Доп. параметры фильтра (пример – минимальный балл по предмету)
    min_score     SMALLINT,

    CONSTRAINT chk_filter_type CHECK (filter_type IN ('region','municipality','institute','school_profile','program','subject','school')),
    CONSTRAINT chk_filter_min_score CHECK (min_score IS NULL OR min_score BETWEEN 0 AND 100),

    -- Для каждого filter_type разрешено заполнение только одного FK
    CONSTRAINT chk_filter_payload CHECK (
        (filter_type='region' AND region_id IS NOT NULL AND municipality_id IS NULL AND institute_id IS NULL AND profile_id IS NULL AND program_id IS NULL AND subject_id IS NULL AND school_id IS NULL AND min_score IS NULL) OR
        (filter_type='municipality' AND municipality_id IS NOT NULL AND region_id IS NULL AND institute_id IS NULL AND profile_id IS NULL AND program_id IS NULL AND subject_id IS NULL AND school_id IS NULL AND min_score IS NULL) OR
        (filter_type='institute' AND institute_id IS NOT NULL AND region_id IS NULL AND municipality_id IS NULL AND profile_id IS NULL AND program_id IS NULL AND subject_id IS NULL AND school_id IS NULL AND min_score IS NULL) OR
        (filter_type='school_profile' AND profile_id IS NOT NULL AND region_id IS NULL AND municipality_id IS NULL AND institute_id IS NULL AND program_id IS NULL AND subject_id IS NULL AND school_id IS NULL AND min_score IS NULL) OR
        (filter_type='program' AND program_id IS NOT NULL AND region_id IS NULL AND municipality_id IS NULL AND institute_id IS NULL AND profile_id IS NULL AND subject_id IS NULL AND school_id IS NULL AND min_score IS NULL) OR
        (filter_type='subject' AND subject_id IS NOT NULL AND region_id IS NULL AND municipality_id IS NULL AND institute_id IS NULL AND profile_id IS NULL AND program_id IS NULL AND school_id IS NULL) OR
        (filter_type='school' AND school_id IS NOT NULL AND region_id IS NULL AND municipality_id IS NULL AND institute_id IS NULL AND profile_id IS NULL AND program_id IS NULL AND subject_id IS NULL AND min_score IS NULL)
    )
);

-- Уникальность элемента фильтра внутри запроса (PostgreSQL: NULL не участвуют в UNIQUE, поэтому используем COALESCE)
CREATE UNIQUE INDEX IF NOT EXISTS uq_req_filter_item ON analytics_request_filter (
    request_id,
    filter_type,
    COALESCE(region_id, -1),
    COALESCE(municipality_id, -1),
    COALESCE(institute_id, -1),
    COALESCE(profile_id, -1),
    COALESCE(program_id, -1),
    COALESCE(subject_id, -1),
    COALESCE(school_id, -1)
);

CREATE INDEX IF NOT EXISTS idx_req_filter_request ON analytics_request_filter(request_id);
CREATE INDEX IF NOT EXISTS idx_req_filter_type ON analytics_request_filter(filter_type);

-- Итоговая выборка школ по запросу (результат применения всех фильтров)
CREATE TABLE IF NOT EXISTS analytics_school_selection (
    request_id  INTEGER NOT NULL REFERENCES analytics_request(request_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    school_id   INTEGER NOT NULL REFERENCES school(school_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    selected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    match_score NUMERIC(5,2),  -- если используется скоринг соответствия фильтрам
    PRIMARY KEY (request_id, school_id)
);

-- Метрика рейтинга (справочник показателей, которые можно включать в расчёт)
CREATE TABLE IF NOT EXISTS analytics_metric (
    metric_code VARCHAR(50) PRIMARY KEY,
    name_ru     TEXT NOT NULL,
    category    VARCHAR(30),  -- ege | admission | prof_orientation | school_info
    unit        VARCHAR(20),
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_metric_category CHECK (category IS NULL OR category IN ('ege', 'admission', 'prof_orientation', 'school_info'))
);

-- Запуск расчёта рейтинга (на основе конкретного запроса)
CREATE TABLE IF NOT EXISTS analytics_rating_run (
    run_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        INTEGER NOT NULL REFERENCES analytics_request(request_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
    calculated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    calculated_by     VARCHAR(100),
    run_name          VARCHAR(200),
    stage             VARCHAR(10) NOT NULL DEFAULT 'final', -- prelim | final
    algorithm_version VARCHAR(32) NOT NULL DEFAULT 'v1',
    normalization     VARCHAR(20) DEFAULT 'minmax',         -- minmax | zscore | rank
    weights_config    JSONB NOT NULL DEFAULT '{}'::jsonb,
    comment           TEXT,

    CONSTRAINT chk_run_stage CHECK (stage IN ('prelim', 'final')),
    CONSTRAINT chk_normalization CHECK (normalization IN ('minmax', 'zscore', 'rank'))
);

-- Метрики, выбранные для запуска (вес + признак основного показателя сортировки)
CREATE TABLE IF NOT EXISTS analytics_run_metric (
    run_id      INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    metric_code VARCHAR(50) NOT NULL REFERENCES analytics_metric(metric_code)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    weight      SMALLINT NOT NULL DEFAULT 1,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (run_id, metric_code),
    CONSTRAINT chk_run_metric_weight CHECK (weight BETWEEN 1 AND 10)
);

-- Ограничение: в одном запуске допускается не более одной "основной" метрики
CREATE UNIQUE INDEX IF NOT EXISTS uq_run_one_primary_metric
ON analytics_run_metric(run_id)
WHERE is_primary = TRUE;

-- Значения метрик по школам в рамках запуска
CREATE TABLE IF NOT EXISTS analytics_school_metric_value (
    run_id         INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
    school_id      INTEGER NOT NULL REFERENCES school(school_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    metric_code    VARCHAR(50) NOT NULL REFERENCES analytics_metric(metric_code)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    raw_value      NUMERIC(14,4),
    norm_value     NUMERIC(14,6),
    weighted_value NUMERIC(14,6),
    PRIMARY KEY (run_id, school_id, metric_code)
);



-- Итоговый рейтинг школ по запуску
CREATE TABLE IF NOT EXISTS analytics_school_rating (
    run_id      INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    school_id   INTEGER NOT NULL REFERENCES school(school_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    rank_pos    INTEGER NOT NULL,
    total_score NUMERIC(12,6) NOT NULL DEFAULT 0,

    year_basis   SMALLINT,
    students_cnt INTEGER,
    ege_avg_all  NUMERIC(5,2),
    top_subjects VARCHAR(200),

    PRIMARY KEY (run_id, school_id),
    CONSTRAINT uq_rank_per_run UNIQUE (run_id, rank_pos),
    CONSTRAINT chk_rank_pos CHECK (rank_pos >= 1),
    CONSTRAINT chk_total_score CHECK (total_score >= 0)
);

-- Витрина по предметам для карточки школы в рамках конкретного запуска рейтинга
-- Формируется на основе базовых таблиц ЕГЭ (факт/план) и состава школ в данном запуске (analytics_school_rating).
CREATE OR REPLACE VIEW analytics_school_subject_snapshot AS
SELECT
    r.run_id,
    sr.school_id,
    subj_ids.subject_id,
    req.year_basis,

    a.avg_score        AS ege_avg_score,
    a.participants_cnt,
    a.not_passed_cnt,
    a.high_80_99_cnt   AS score_80_99_cnt,
    a.score_100_cnt,

    p.chosen_cnt,
    CASE
        WHEN y_p.graduates_total > 0 AND p.chosen_cnt IS NOT NULL
        THEN ROUND((p.chosen_cnt::NUMERIC * 100) / y_p.graduates_total, 2)
    END AS chosen_pct
FROM analytics_rating_run r
JOIN analytics_request req ON req.request_id = r.request_id
JOIN analytics_school_rating sr ON sr.run_id = r.run_id
LEFT JOIN ege_school_year y_a
       ON y_a.school_id = sr.school_id AND y_a.year = req.year_basis AND y_a.kind = 'actual'
LEFT JOIN ege_school_year y_p
       ON y_p.school_id = sr.school_id AND y_p.year = req.year_basis AND y_p.kind = 'plan'
JOIN LATERAL (
    SELECT DISTINCT s.subject_id
    FROM ege_school_subject_stat s
    WHERE (y_a.ege_school_year_id IS NOT NULL AND s.ege_school_year_id = y_a.ege_school_year_id)
       OR (y_p.ege_school_year_id IS NOT NULL AND s.ege_school_year_id = y_p.ege_school_year_id)
) subj_ids ON TRUE
LEFT JOIN ege_school_subject_stat a
       ON y_a.ege_school_year_id IS NOT NULL
      AND a.ege_school_year_id = y_a.ege_school_year_id
      AND a.subject_id = subj_ids.subject_id
LEFT JOIN ege_school_subject_stat p
       ON y_p.ege_school_year_id IS NOT NULL
      AND p.ege_school_year_id = y_p.ege_school_year_id
      AND p.subject_id = subj_ids.subject_id;


-- Карточка школы (агрегации для выдачи пользователю в одном объекте)
-- Хранится как JSON, чтобы не усложнять схему при расширении набора полей.
CREATE TABLE IF NOT EXISTS analytics_school_card (
    card_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                 ON UPDATE CASCADE ON DELETE CASCADE,
    school_id    INTEGER NOT NULL REFERENCES school(school_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    school_info       JSONB NOT NULL DEFAULT '{}'::jsonb,
    ege_summary       JSONB NOT NULL DEFAULT '{}'::jsonb,
    admission_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    prof_summary      JSONB NOT NULL DEFAULT '{}'::jsonb,
    conclusions       JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT uq_card_per_run_school UNIQUE (run_id, school_id)
);

-- Отчёт по школе (разные форматы представления на основе карточки/метрик)
CREATE TABLE IF NOT EXISTS analytics_school_report (
    report_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
    school_id      INTEGER NOT NULL REFERENCES school(school_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    report_type    VARCHAR(20) NOT NULL DEFAULT 'standard', -- standard | detailed | comparison | timeline
    generated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    report_format  VARCHAR(10) DEFAULT 'json',             -- json | html | pdf
    report_payload JSONB NOT NULL,

    CONSTRAINT chk_report_type CHECK (report_type IN ('standard', 'detailed', 'comparison', 'timeline')),
    CONSTRAINT chk_report_format CHECK (report_format IN ('json', 'html', 'pdf'))
);

-- Индексы под типовые выборки
CREATE INDEX IF NOT EXISTS idx_municipality_region_id ON municipality(region_id);
CREATE INDEX IF NOT EXISTS idx_school_municipality_id ON school(municipality_id);
CREATE INDEX IF NOT EXISTS idx_school_external_key_school_id ON school_external_key(school_id);
CREATE INDEX IF NOT EXISTS idx_school_profile_link_school ON school_profile_link(school_id);
CREATE INDEX IF NOT EXISTS idx_school_profile_link_profile ON school_profile_link(profile_id);

CREATE INDEX IF NOT EXISTS idx_ege_school_year_school_year_kind ON ege_school_year(school_id, year, kind);
CREATE INDEX IF NOT EXISTS idx_ege_school_year_year ON ege_school_year(year);
CREATE INDEX IF NOT EXISTS idx_ege_subject_stat_year_subject ON ege_school_subject_stat(ege_school_year_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_ege_subject_stat_avg_score ON ege_school_subject_stat(avg_score);

CREATE INDEX IF NOT EXISTS idx_study_program_institute_id ON study_program(institute_id);
CREATE INDEX IF NOT EXISTS idx_program_ege_req_program_id ON program_ege_requirement(program_id);
CREATE INDEX IF NOT EXISTS idx_program_ege_req_subject_id ON program_ege_requirement(subject_id);

CREATE INDEX IF NOT EXISTS idx_prof_event_school_date ON prof_event(school_id, event_date);
CREATE INDEX IF NOT EXISTS idx_prof_event_date ON prof_event(event_date);

CREATE INDEX IF NOT EXISTS idx_admission_stat_school_year ON school_admission_stat(school_id, year);
CREATE INDEX IF NOT EXISTS idx_admission_stat_year ON school_admission_stat(year);
CREATE INDEX IF NOT EXISTS idx_admission_detail_stat_program ON school_admission_detail(adm_stat_id, program_id);

CREATE INDEX IF NOT EXISTS idx_analytics_request_created ON analytics_request(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_request_scenario ON analytics_request(scenario);
CREATE INDEX IF NOT EXISTS idx_analytics_request_year ON analytics_request(year_basis);

CREATE INDEX IF NOT EXISTS idx_school_selection_request ON analytics_school_selection(request_id);
CREATE INDEX IF NOT EXISTS idx_school_selection_school ON analytics_school_selection(school_id);
CREATE INDEX IF NOT EXISTS idx_school_selection_match ON analytics_school_selection(match_score DESC) WHERE match_score IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rating_run_request ON analytics_rating_run(request_id);
CREATE INDEX IF NOT EXISTS idx_rating_run_created ON analytics_rating_run(calculated_at DESC);
CREATE INDEX IF NOT EXISTS idx_rating_run_stage ON analytics_rating_run(stage);

CREATE INDEX IF NOT EXISTS idx_run_metric_run ON analytics_run_metric(run_id);
CREATE INDEX IF NOT EXISTS idx_metric_value_run_school ON analytics_school_metric_value(run_id, school_id);
CREATE INDEX IF NOT EXISTS idx_metric_value_metric ON analytics_school_metric_value(metric_code);

CREATE INDEX IF NOT EXISTS idx_school_rating_run ON analytics_school_rating(run_id);
CREATE INDEX IF NOT EXISTS idx_school_rating_rank ON analytics_school_rating(run_id, rank_pos);
CREATE INDEX IF NOT EXISTS idx_school_rating_score ON analytics_school_rating(total_score DESC);

CREATE INDEX IF NOT EXISTS idx_school_card_run ON analytics_school_card(run_id);
CREATE INDEX IF NOT EXISTS idx_school_card_school ON analytics_school_card(school_id);
CREATE INDEX IF NOT EXISTS idx_school_report_run ON analytics_school_report(run_id);
CREATE INDEX IF NOT EXISTS idx_school_report_type ON analytics_school_report(report_type);

-- Комментарии к таблицам
COMMENT ON TABLE region IS 'Справочник регионов';
COMMENT ON TABLE municipality IS 'Справочник муниципалитетов (внутри регионов)';
COMMENT ON TABLE school IS 'Справочник школ';
COMMENT ON TABLE school_profile IS 'Справочник профилей школ';
COMMENT ON TABLE school_profile_link IS 'Связь школа–профиль (у школы может быть несколько профилей)';
COMMENT ON TABLE school_external_key IS 'Сопоставление школ между источниками данных';
COMMENT ON TABLE ege_subject IS 'Справочник предметов ЕГЭ';
COMMENT ON TABLE ege_school_year IS 'ЕГЭ по школе за год (агрегаты)';
COMMENT ON TABLE ege_school_subject_stat IS 'ЕГЭ по предмету: показатели факта (actual) и план/выбор (plan) в единой таблице';
COMMENT ON TABLE analytics_request_filter IS 'Фильтры (множественный выбор) для аналитического запроса';
COMMENT ON VIEW analytics_school_subject_snapshot IS 'Витрина: показатели по предметам для карточки школы в рамках запуска рейтинга';
COMMENT ON TABLE institute IS 'Справочник институтов';
COMMENT ON TABLE study_program IS 'Справочник направлений подготовки';
COMMENT ON TABLE program_ege_requirement IS 'Требования ЕГЭ для направления (роль и вес)';
COMMENT ON TABLE prof_event IS 'Проведённые профориентационные мероприятия';
COMMENT ON TABLE school_admission_stat IS 'Итоги приёма по школе за год (агрегаты)';
COMMENT ON TABLE school_admission_detail IS 'Детализация приёма по направлениям (опционально)';
COMMENT ON TABLE analytics_request IS 'Запрос пользователя с параметрами отбора';
COMMENT ON TABLE analytics_school_selection IS 'Итоговая выборка школ по запросу';
COMMENT ON TABLE analytics_metric IS 'Справочник метрик для расчёта рейтинга';
COMMENT ON TABLE analytics_rating_run IS 'Запуск расчёта рейтинга по запросу';
COMMENT ON TABLE analytics_run_metric IS 'Набор метрик и весов для конкретного запуска';
COMMENT ON TABLE analytics_school_metric_value IS 'Значения метрик по школам в рамках запуска';
COMMENT ON TABLE analytics_school_rating IS 'Итоговый рейтинг школ по запуску';
COMMENT ON TABLE analytics_school_card IS 'Карточка школы (агрегированные данные в JSON)';
COMMENT ON TABLE analytics_school_report IS 'Отчёт по школе (формат/тип + payload)';

COMMIT;
