CREATE SCHEMA IF NOT EXISTS edu;
SET search_path TO edu;

-- Справочники территорий
CREATE TABLE IF NOT EXISTS region (
    region_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    CONSTRAINT uq_region_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS municipality (
    municipality_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id       INTEGER NOT NULL REFERENCES region(region_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
    name            TEXT NOT NULL,
    CONSTRAINT uq_municipality_region_name UNIQUE (region_id, name)
);

-- Справочники школ
CREATE TABLE IF NOT EXISTS school (
    school_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipality_id INTEGER NOT NULL REFERENCES municipality(municipality_id)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
    full_name       TEXT NOT NULL,
is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_school_municipality_full_name UNIQUE (municipality_id, full_name)
);

CREATE TABLE IF NOT EXISTS school_profile (
    profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS school_profile_link (
    school_id  INTEGER NOT NULL REFERENCES school(school_id)
               ON UPDATE CASCADE ON DELETE CASCADE,
    profile_id INTEGER NOT NULL REFERENCES school_profile(profile_id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (school_id, profile_id)
);

CREATE TYPE source_system AS ENUM ('EGE', 'ONEC', 'BITRIX24');
CREATE TABLE IF NOT EXISTS school_external_key (
    ext_key_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES school(school_id)
                    ON UPDATE CASCADE ON DELETE CASCADE,
    source_name     source_system NOT NULL,
    external_key    TEXT NOT NULL,
    normalized_name TEXT,
    CONSTRAINT uq_source_external_key UNIQUE (source_name, external_key),
    CONSTRAINT uq_school_source UNIQUE (school_id, source_name)
);

-- ЕГЭ: справочник предметов
CREATE TABLE IF NOT EXISTS ege_subject (
    subject_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    min_pass_score  SMALLINT NOT NULL,
    CONSTRAINT uq_subject_name UNIQUE (name),
    CONSTRAINT chk_min_pass_score CHECK (min_pass_score BETWEEN 0 AND 100)
);

-- ЕГЭ: фактические результаты по школе и предметам
CREATE TABLE IF NOT EXISTS ege_school_year (
    ege_school_year_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          INTEGER NOT NULL REFERENCES school(school_id)
                       ON UPDATE CASCADE ON DELETE CASCADE,
    year               SMALLINT NOT NULL,
    graduates_total    INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_ege_school_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_ege_graduates_total CHECK (graduates_total >= 0),
    CONSTRAINT uq_ege_school_year UNIQUE (school_id, year)
);

CREATE TABLE IF NOT EXISTS ege_school_subject_result (
    ege_subject_result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ege_school_year_id    INTEGER NOT NULL REFERENCES ege_school_year(ege_school_year_id)
                          ON UPDATE CASCADE ON DELETE CASCADE,
    subject_id            INTEGER NOT NULL REFERENCES ege_subject(subject_id)
                          ON UPDATE CASCADE ON DELETE RESTRICT,
    participants_cnt      INTEGER NOT NULL DEFAULT 0,
    not_passed_cnt        INTEGER NOT NULL DEFAULT 0,
    high_80_99_cnt        INTEGER NOT NULL DEFAULT 0,
    score_100_cnt         INTEGER NOT NULL DEFAULT 0,
    avg_score             NUMERIC(5,2),
    CONSTRAINT uq_ege_subject_per_year UNIQUE (ege_school_year_id, subject_id),
    CONSTRAINT chk_participants_nonneg CHECK (participants_cnt >= 0),
    CONSTRAINT chk_not_passed_nonneg CHECK (not_passed_cnt >= 0),
    CONSTRAINT chk_high_80_99_nonneg CHECK (high_80_99_cnt >= 0),
    CONSTRAINT chk_score_100_nonneg CHECK (score_100_cnt >= 0),
    CONSTRAINT chk_not_passed_le_participants CHECK (not_passed_cnt <= participants_cnt),
    CONSTRAINT chk_high_80_99_le_participants CHECK (high_80_99_cnt <= participants_cnt),
    CONSTRAINT chk_score_100_le_participants CHECK (score_100_cnt <= participants_cnt),
    CONSTRAINT chk_avg_score_range CHECK (avg_score IS NULL OR (avg_score BETWEEN 0 AND 100))
);


-- ЕГЭ: план выбора предметов (предварительные данные)
CREATE TABLE IF NOT EXISTS ege_choice_school_year (
    choice_school_year_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id             INTEGER NOT NULL REFERENCES school(school_id)
                          ON UPDATE CASCADE ON DELETE CASCADE,
    year                  SMALLINT NOT NULL,
    graduates_total       INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_choice_school_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_choice_graduates_total CHECK (graduates_total >= 0),
    CONSTRAINT uq_choice_school_year UNIQUE (school_id, year)
);

CREATE TABLE IF NOT EXISTS ege_choice_school_subject (
    choice_school_subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    choice_school_year_id    INTEGER NOT NULL REFERENCES ege_choice_school_year(choice_school_year_id)
                             ON UPDATE CASCADE ON DELETE CASCADE,
    subject_id               INTEGER NOT NULL REFERENCES ege_subject(subject_id)
                             ON UPDATE CASCADE ON DELETE RESTRICT,
    chosen_cnt               INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_choice_subject_per_year UNIQUE (choice_school_year_id, subject_id),
    CONSTRAINT chk_chosen_cnt_nonneg CHECK (chosen_cnt >= 0)
);


-- Справочники приёма: институты и направления
CREATE TABLE IF NOT EXISTS institute (
    institute_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    CONSTRAINT uq_institute_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS study_program (
    program_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institute_id INTEGER NOT NULL REFERENCES institute(institute_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    code         VARCHAR(20) NOT NULL,
    name         TEXT NOT NULL,
    CONSTRAINT uq_program_code UNIQUE (code)
);

-- Требования к ЕГЭ по направлению
CREATE TABLE IF NOT EXISTS program_ege_requirement (
    req_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id   INTEGER NOT NULL REFERENCES study_program(program_id)
                 ON UPDATE CASCADE ON DELETE CASCADE,
    subject_id   INTEGER NOT NULL REFERENCES ege_subject(subject_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,

    role         VARCHAR(10) NOT NULL,      -- 'required' | 'choice'
    weight       SMALLINT NOT NULL,         -- только 1,2,3

    CONSTRAINT chk_req_role CHECK (role IN ('required', 'choice')),
    CONSTRAINT chk_req_weight CHECK (weight IN (1, 2, 3)),

    -- правило: weight=1 => предмет всегда обязательный
    CONSTRAINT chk_weight1_is_required CHECK (weight <> 1 OR role = 'required'),

    -- предмет по выбору не может иметь вес 1
    CONSTRAINT chk_choice_weight CHECK (role <> 'choice' OR weight IN (2, 3)),

    -- один предмет нельзя дважды указать для одного направления
    CONSTRAINT uq_program_subject UNIQUE (program_id, subject_id)
);

-- Профориентация (Битрикс24) – история взаимодействий
CREATE TABLE IF NOT EXISTS prof_event (
    event_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     INTEGER NOT NULL REFERENCES school(school_id)
                  ON UPDATE CASCADE ON DELETE CASCADE,
    institute_id  INTEGER NOT NULL REFERENCES institute(institute_id)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
    event_date    DATE NOT NULL,
    coverage_cnt  INTEGER NOT NULL DEFAULT 0,
    external_key  TEXT,
    CONSTRAINT chk_coverage_nonneg CHECK (coverage_cnt >= 0)
);


-- 8) Итоги приёма (1С) – агрегаты по школе и году
CREATE TABLE IF NOT EXISTS school_admission_stat (
    adm_stat_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES school(school_id)
                        ON UPDATE CASCADE ON DELETE CASCADE,
    year                SMALLINT NOT NULL,
    applicants_cnt      INTEGER NOT NULL DEFAULT 0,
    enrolled_cnt        INTEGER NOT NULL DEFAULT 0,
    enrolled_avg_score  NUMERIC(5,2),
    external_key        TEXT,
    CONSTRAINT chk_adm_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_applicants_nonneg CHECK (applicants_cnt >= 0),
    CONSTRAINT chk_enrolled_nonneg CHECK (enrolled_cnt >= 0),
    CONSTRAINT chk_enrolled_le_applicants CHECK (enrolled_cnt <= applicants_cnt),
    CONSTRAINT chk_enrolled_avg_score_range CHECK (
        enrolled_avg_score IS NULL OR (enrolled_avg_score BETWEEN 0 AND 100)
    ),
    CONSTRAINT uq_school_adm_year UNIQUE (school_id, year)
);


-- 9) Таблицы для результатов (DFD: параметры запроса, выборка, рейтинг, отчёты, экспорт)


-- Аналитика: Запрос пользователя (параметры отбора/поиска)
-- Важно: множественные фильтры (регионы/муниципалитеты/институты/профили) вынесены в отдельные таблицы ниже.
CREATE TABLE IF NOT EXISTS analytics_request (
    request_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    scenario     VARCHAR(12) NOT NULL,   -- selection | search
    year_basis   SMALLINT,               -- год, по которому считаем/сравниваем (ЕГЭ/приём)
    only_active  BOOLEAN NOT NULL DEFAULT TRUE,
    notes        TEXT,

    CONSTRAINT chk_req_scenario CHECK (scenario IN ('selection', 'search')),
    CONSTRAINT chk_req_year_basis CHECK (year_basis IS NULL OR (year_basis BETWEEN 2000 AND 2100))
);

-- Аналитика: Отбор по регионам (можно выбрать несколько)
CREATE TABLE IF NOT EXISTS analytics_request_region (
    request_id INTEGER NOT NULL REFERENCES analytics_request(request_id)
               ON UPDATE CASCADE ON DELETE CASCADE,
    region_id  INTEGER NOT NULL REFERENCES region(region_id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, region_id)
);

-- Аналитика: Отбор по муниципалитетам (можно выбрать несколько)
CREATE TABLE IF NOT EXISTS analytics_request_municipality (
    request_id       INTEGER NOT NULL REFERENCES analytics_request(request_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
    municipality_id  INTEGER NOT NULL REFERENCES municipality(municipality_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, municipality_id)
);

-- Аналитика: Отбор по институтам (можно выбрать несколько)
CREATE TABLE IF NOT EXISTS analytics_request_institute (
    request_id   INTEGER NOT NULL REFERENCES analytics_request(request_id)
                 ON UPDATE CASCADE ON DELETE CASCADE,
    institute_id INTEGER NOT NULL REFERENCES institute(institute_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, institute_id)
);

-- Аналитика: Отбор по профилям школ (если у тебя уже есть справочник профилей)
-- Если справочника профилей ещё нет – можно временно заменить profile_id на profile_text TEXT.
CREATE TABLE IF NOT EXISTS analytics_request_school_profile (
    request_id  INTEGER NOT NULL REFERENCES analytics_request(request_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    profile_id  INTEGER NOT NULL REFERENCES school_profile(profile_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, profile_id)
);

-- Аналитика: Выбранные направления в запросе (можно выбрать несколько)
CREATE TABLE IF NOT EXISTS analytics_request_program (
    request_id INTEGER NOT NULL REFERENCES analytics_request(request_id)
               ON UPDATE CASCADE ON DELETE CASCADE,
    program_id INTEGER NOT NULL REFERENCES study_program(program_id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, program_id)
);

-- Аналитика: Отбор по предметам в запросе (можно выбрать несколько)
CREATE TABLE IF NOT EXISTS analytics_request_subject (
    request_id  INTEGER NOT NULL REFERENCES analytics_request(request_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    subject_id  INTEGER NOT NULL REFERENCES ege_subject(subject_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, subject_id)
);

-- Аналитика: Список школ, заданный пользователем (сценарий 'search')
CREATE TABLE IF NOT EXISTS analytics_request_school (
    request_id INTEGER NOT NULL REFERENCES analytics_request(request_id)
               ON UPDATE CASCADE ON DELETE CASCADE,
    school_id  INTEGER NOT NULL REFERENCES school(school_id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (request_id, school_id)
);

-- Аналитика: Итоговая выборка школ по запросу (после применения всех фильтров)
CREATE TABLE IF NOT EXISTS analytics_school_selection (
    request_id  INTEGER NOT NULL REFERENCES analytics_request(request_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    school_id   INTEGER NOT NULL REFERENCES school(school_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    selected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (request_id, school_id)
);


-- Аналитика: Запуск расчёта рейтинга
-- stage позволяет разделить расчёт "по результатам" и "по предварительным данным".
CREATE TABLE IF NOT EXISTS analytics_rating_run (
    run_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        INTEGER NOT NULL REFERENCES analytics_request(request_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
    calculated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    stage             VARCHAR(10) NOT NULL DEFAULT 'final', -- prelim | final
    algorithm_version VARCHAR(32) NOT NULL DEFAULT 'v1',
    weights           JSONB NOT NULL DEFAULT '{}'::jsonb,
    comment           TEXT,

    CONSTRAINT chk_run_stage CHECK (stage IN ('prelim', 'final'))
);


-- Аналитика: Справочник показателей (что вообще можно выводить/использовать в рейтинге)
-- metric_code – стабильный код показателя, например:
-- 'ege_avg', 'ege_100', 'ege_80_99', 'admission_enrolled', 'prof_event_cnt', 'choice_cnt'
CREATE TABLE IF NOT EXISTS analytics_metric (
    metric_code VARCHAR(50) PRIMARY KEY,
    name_ru     TEXT NOT NULL,
    unit        VARCHAR(20),  -- 'балл', 'чел', '%', и т.п.
    description TEXT
);

-- Аналитика: Выбранные показатели для конкретного запуска (что именно считать и показывать)
-- weight – твои веса 1/2/3, если используешь их в расчёте.
CREATE TABLE IF NOT EXISTS analytics_run_metric (
    run_id      INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                ON UPDATE CASCADE ON DELETE CASCADE,
    metric_code VARCHAR(50) NOT NULL REFERENCES analytics_metric(metric_code)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    weight      SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (run_id, metric_code),
    CONSTRAINT chk_run_metric_weight CHECK (weight IN (1,2,3))
);

-- Аналитика: Значения показателей по школе в рамках запуска
CREATE TABLE IF NOT EXISTS analytics_school_metric_value (
    run_id        INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                  ON UPDATE CASCADE ON DELETE CASCADE,
    school_id     INTEGER NOT NULL REFERENCES school(school_id)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
    metric_code   VARCHAR(50) NOT NULL REFERENCES analytics_metric(metric_code)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
    raw_value     NUMERIC(14,4),
    norm_value    NUMERIC(14,6),     -- если нормируешь (0..1)
    contribution  NUMERIC(14,6),     -- вклад в total_score (если применяешь)
    PRIMARY KEY (run_id, school_id, metric_code)
);


-- Аналитика: Предметный срез по школе для карточки/отчёта (чтобы выводить сразу несколько предметов)
-- Заполняется по предметам из analytics_request_subject (или по всем, если предметы не заданы).
CREATE TABLE IF NOT EXISTS analytics_school_subject_snapshot (
    run_id         INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
    school_id      INTEGER NOT NULL REFERENCES school(school_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    subject_id     INTEGER NOT NULL REFERENCES ege_subject(subject_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    year_basis     SMALLINT,
    -- фактические показатели ЕГЭ (если run.stage='final')
    ege_avg_score      NUMERIC(5,2),
    participants_cnt   INTEGER,
    not_passed_cnt     INTEGER,
    high_80_99_cnt     INTEGER,
    score_100_cnt      INTEGER,
    -- предварительные показатели (если run.stage='prelim')
    chosen_cnt         INTEGER,
    PRIMARY KEY (run_id, school_id, subject_id)
);


-- Аналитика: Рейтинг школ (итоги расчёта)
-- total_score/rank_pos – итог, а детализация по выбранным показателям лежит в analytics_school_metric_value.
CREATE TABLE IF NOT EXISTS analytics_school_rating (
    run_id         INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
    school_id      INTEGER NOT NULL REFERENCES school(school_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,

    year_basis     SMALLINT,
    rank_pos       INTEGER NOT NULL,
    total_score    NUMERIC(12,6) NOT NULL DEFAULT 0,

    metrics        JSONB NOT NULL DEFAULT '{}'::jsonb, -- быстрые агрегаты/служебные поля

    PRIMARY KEY (run_id, school_id),
    CONSTRAINT uq_rank_per_run UNIQUE (run_id, rank_pos),
    CONSTRAINT chk_rank_pos CHECK (rank_pos >= 1),
    CONSTRAINT chk_total_score CHECK (total_score >= 0)
);


-- Аналитика: Отчёт по школе (карточка/детализация)
-- report_type позволяет хранить несколько форматов по одной школе в одном run: 'card' и 'detail'.
-- report_payload хранит полный пакет данных по школе (территория, ЕГЭ по годам, приём, профориентация, выводы).
CREATE TABLE IF NOT EXISTS analytics_school_report (
    report_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                   ON UPDATE CASCADE ON DELETE CASCADE,
    school_id      INTEGER NOT NULL REFERENCES school(school_id)
                   ON UPDATE CASCADE ON DELETE RESTRICT,
    report_type    VARCHAR(10) NOT NULL DEFAULT 'card', -- card | detail
    generated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    report_payload JSONB NOT NULL,

    CONSTRAINT chk_report_type CHECK (report_type IN ('card', 'detail')),
    CONSTRAINT uq_report_per_run_school_type UNIQUE (run_id, school_id, report_type)
);


-- Аналитика: Экспорт результатов (Excel и т.п.)
CREATE TABLE IF NOT EXISTS analytics_export_log (
    export_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       INTEGER NOT NULL REFERENCES analytics_rating_run(run_id)
                 ON UPDATE CASCADE ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    export_type  VARCHAR(20) NOT NULL, -- rating | school_report | both
    file_name    TEXT,
    meta         JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT chk_export_type CHECK (export_type IN ('rating', 'school_report', 'both'))
);

-- Индексы под частые фильтры/соединения
CREATE INDEX IF NOT EXISTS idx_municipality_region_id ON municipality(region_id);
CREATE INDEX IF NOT EXISTS idx_school_municipality_id ON school(municipality_id);
CREATE INDEX IF NOT EXISTS idx_school_external_key_school_id ON school_external_key(school_id);
CREATE INDEX IF NOT EXISTS idx_ege_school_year_school_id_year ON ege_school_year(school_id, year);
CREATE INDEX IF NOT EXISTS idx_ege_subject_result_year_subject ON ege_school_subject_result(ege_school_year_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_choice_school_year_school_id_year ON ege_choice_school_year(school_id, year);
CREATE INDEX IF NOT EXISTS idx_choice_school_subject_year_subject ON ege_choice_school_subject(choice_school_year_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_study_program_institute_id ON study_program(institute_id);
CREATE INDEX IF NOT EXISTS idx_req_program_id ON program_ege_requirement(program_id);
CREATE INDEX IF NOT EXISTS idx_prof_event_school_id_date ON prof_event(school_id, event_date);
CREATE INDEX IF NOT EXISTS idx_adm_stat_school_id_year ON school_admission_stat(school_id, year);

CREATE INDEX IF NOT EXISTS idx_req_region ON analytics_request(region_id);
CREATE INDEX IF NOT EXISTS idx_req_municipality ON analytics_request(municipality_id);
CREATE INDEX IF NOT EXISTS idx_sel_request ON analytics_school_selection(request_id);
CREATE INDEX IF NOT EXISTS idx_rating_run_request ON analytics_rating_run(request_id);
CREATE INDEX IF NOT EXISTS idx_school_rating_rank ON analytics_school_rating(run_id, rank_pos);
CREATE INDEX IF NOT EXISTS idx_school_profile_link_profile ON school_profile_link(profile_id, school_id);

COMMENT ON SCHEMA edu IS 'Курсовая: отбор школ для профориентации на основе данных ЕГЭ, приёма и профориентации';